version: "3"
services:
  web: 
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - .:/app
  composer:
    image: composer/composer
    command: composer dump-autoload
    volumes:
      - .:/app